name: Load secrets from Dashlane
description: Makes it possible to inject secrets from your vault in a CI using the Dashlane CLI.
author: Dashlane
branding:
  icon: key
  color: grey
runs:
  using: composite
  steps:
    # install cli
    - name: install-cli
      run: ./install.sh
      shell: bash
    # Get credentials from env variables
    # run the dcli read command and eco the output to Github Output
    - name: get-secret
      shell: bash
      run: ./script.sh
