name: Load secrets from Dashlane
description: Makes it possible to inject secrets from your vault in a CI using the Dashlane CLI.
author: Dashlane
branding:
  icon: key
  color: grey
runs:
  using: composite
  steps:
    # install cli
    - name: Install cli
      run: ./install-cli.sh
      shell: bash
    # Get credentials from env variables
    # run the dcli read command and eco the output to Github Output
    - name: Run script
      shell: bash
      env:
        DASHLANE_DEVICE_ACCESS_KEY: ${{ secrets.DASHLANE_DEVICE_ACCESS_KEY }}
        DASHLANE_DEVICE_SECRET_KEY: ${{ secrets.DASHLANE_DEVICE_SECRET_KEY }}
        DASHLANE_LOGIN: ${{ secrets.DASHLANE_LOGIN }}
        DASHLANE_MASTER_PASSWORD: ${{ secrets.DASHLANE_MASTER_PASSWORD }}
      run: | 
      ./script.sh
      
