name: test_dashlane_action

on: push

jobs:
  test_action:
    name: Load secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Load secrets
        id: load_secrets
        uses: ./ # Dashlane/github-action@<version>
        env:
          ACTION_SECRET: dl://918E3113-CA48-4642-8FAF-CE832BDED6BE/password
      - name: Assert test secret values
        env:
          ACTION_SECRET: ${{ steps.load_secrets.outputs.ACTION_SECRET }}
        run: ./test.sh
