name: Verify

on: push

jobs:
  test_action:
    name: Load secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Load secrets
        id: load_secrets
        uses: ./ # Dashlane/github-action@<version>
        env:
          ACTION_SECRET: dl://331CB092-FECF-49F5-A8B6-5279BC543011/password
          DASHLANE_DEVICE_ACCESS_KEY: ${{ secrets.DASHLANE_DEVICE_ACCESS_KEY }}
          DASHLANE_DEVICE_SECRET_KEY: ${{ secrets.DASHLANE_DEVICE_SECRET_KEY }}
          DASHLANE_LOGIN: ${{ secrets.DASHLANE_LOGIN }}
          DASHLANE_MASTER_PASSWORD: ${{ secrets.DASHLANE_MASTER_PASSWORD }}
      - name: Assert test secret values
        run: ./test.sh
